export const en = {
  naviHello: 'Hello,',
  naviHome: 'Home',
  naviLogin: 'Log in',
  naviSettings: 'Settings',
  naviData: 'Data',
  naviAbout: 'About',
  naviLogout: 'Log out',
  labelAge: 'Age',
  labelDose: 'Total gonadotropin dose, IU',
  labelOocytes: 'Number of oocytes retrieved',
  labelCleaving: 'Number of cleaving embryos on day 2/3',
  labelTop: 'Number of top-quality embryos on day 2/3',
  labelDiagnosis: 'Diagnosis',
  labelStatus: 'Status',
  labelDoctor: 'Doctor',
  labelPatient: 'Patient',
  btnSubmit: 'Submit',
  stimulation: 'Stimulation',
  addStimulation: 'Add stimulation',
  rmvStimulation: 'Remove stimulation',
  selectChoose: 'Please choose',
  selectUnexplained: 'Unexplained',
  selectEndo: 'Endometriosis',
  selectAno: 'Anovulation',
  selectMalef: 'Male factor',
  selectTubal: 'Tubal factor',
  mainTitle: 'Probability of live birth after IVF/ICSI treatment',
  mainContent1: 'This site calculates the probability of live birth after one or several IVF/ICSI treatments using the couple’s own gametes (oocytes and sperm). These treatments include all possible transfers with frozen-thawed embryos as well. We use input from clinical and laboratory factors of the fresh, stimulation cycle in order to make predictions as precise as possible. You can find more information on the calculation methods in the',
  mainAbout: 'About',
  mainContent2: 'section.',
  infoTitle: 'Information about input variables',
  infoAgeTitle: 'Age:',
  infoAge: 'age on the day of oocyte pickup, in years.',
  infoGonaTitle: 'Total gonadotropin dose, IU:',
  infoGona: 'total dose or recombinant or purified human menopausal FSH in IU.',
  infoOocTitle: 'Number of oocytes retrieved:',
  infoOoc: 'number of mature and immature oocytes retrieved.',
  infoCleavTitle: 'Number of cleaving embryos on day 2/3:',
  infoCleav: 'if you are having a transfer on day 2, please insert the number of cleaving (dividing) embryos on day 2. For all other cases, please insert the number of cleaving embryos on day 3.',
  infoTopTitle: 'Number of top-quality embryos on day 2/3:',
  infoTop1: 'if you are having a transfer on day 2, please insert the number of top-quality embryos on day 2. For all other cases, please insert the number of top-quality embryos on day 3. Criteria for embryo scoring can be found in the',
  infoTopAbout: 'About',
  infoTop2: 'section.',
  infoDiagnosisTitle: 'Diagnosis:',
  infoDiagnosis: 'please choose only one main infertility diagnosis.',
  addUser: 'Add user',
  old_password: 'old password',
  new_password: 'new password',
  admin_country: 'Country',
  admin_status: 'Status',
  admin_diagnosis: 'Diagnosis',
  admin_age: 'Age',
  admin_dose: 'Dose',
  admin_oocytes: 'Oocytes',
  admin_cleaving: 'Cleaving',
  admin_top: 'Top',
  admin_stimulation: 'Stimulation',
  admin_cumulative_probability: 'Cumulative Probability',
  admin_probability: 'Probability',
  admin_date: 'Date',
  admin_start_date: 'Start date',
  admin_end_date: 'End date',
  admin_filter: 'Filter',
  admin_export: 'Export to Excel',
  chart_cumulative_probability: 'Cumulative probability for treatments with completed stimulations',
  chart_max_cumulative: 'Maximum cumulative probability prediction',
  chart_min_cumulative: 'Minimum cumulative probability prediction',
  chart_x_axis_label: 'Treatment number',
  chart_y_axis_label: 'Probability of live birth after treatment',
  aboutH1: 'About',
  aboutH2_1: 'How do we calculate predictions?',
  aboutP1_1: 'The statistical basis for the calculator comes from a retrospective study of 13,000 ovarian stimulation cycles and their following 10,000 transfers of frozen-thawed embryos (Development and external validation of prediction model for cumulative live birth after IVF/ICSI using ovarian response and embryo cohort quality data of 11,461 Finnish women by Zdravka Veleva, Henna Oksanen, Anna But, Sirpa Mäkinen, Helena Tinkanen, Christel Hydén-Granskog, Niklas Simberg, Hannu Martikainen, Aila Tiitinen, and  Juha S. Tapanainen). Data for this study came from the infertility units of Helsinki, Oulu and Tampere University Hospitals, and the private Väestöliitto fertility clinics in Helsinki and Oulu.',
  aboutP1_2: 'You can insert data from your treatment cycle in order to calculate predictions for the outcome of the fresh (stimulation) cycle and all cycles using cryopreserved embryos from the same stimulation. Just use the appropriate boxes for each parameter.',
  aboutP1_3: 'You can also calculate the chance of live birth using data from more than one cycle. The calculator will then present the cumulative probability of live birth after up to five stimulations.',
  aboutP1_4: 'Concerning the chance of live birth for treatments that are not yet performed: based on your input, the calculator will create optimistic and pessimistic predictions based on your best and worst treatments. If you have only had one stimulation, the calculator will base its predictions on that cycle.',
  aboutP1_5: 'Our predictions do not depend on the number of embryos transferred in the fresh cycle, the day of embryo transfer (ranging from day 2 to day 6), or on the type of ovarian stimulations because in our calculator, we use stronger predictive factors.',
  aboutH2_2: 'How accurate are the predictions?',
  aboutP2_1: 'At present, this calculator gives the best predictions of cumulative live birth after one or several IVF/ICSI treatments, including the outcome of frozen-thawed embryo transfers. However, there is a certain amount of uncertainty regarding the predictions because different factors, especially the ones regarding embryo genetic composition and frozen-thawed embryo transfer, cannot be completely evaluated. The prognostic power of the model on which the calculator is based was evaluated in different manners. The model can distinguish between patients and treatments with high probability of live birth from those with low probabilities with a rate of 0.72. For comparison, 0.50 is random guessing and 1.00 is complete match with clinical outcome. However, model-predicted and observed probabilities were very close in the study, with P=0.99 (P=1.0 is the perfect match).',
  aboutP2_2: 'The purpose of this site is not to give a definitive number but rather to show how different background and treatment factors interact and affect the chance of live birth. If you want a more complete prognosis, please ask your doctor!',
  aboutP2_3: '',
  aboutH2_3: 'Number of embryos transferred',
  aboutP3_1: 'The probability of live birth is the same after one and after two embryos transferred provided no more than one top-quality embryo has been transferred. Transfer of >1 top-quality embryo is not advisable because of the considerably higher risk of multiple pregnancy and complications. If only one embryo is transferred in the fresh cycle, there are more embryos to freeze and transfer at a later time.',
  aboutH2_4: 'Day of embryo transfer',
  aboutP4_1: 'Our model was developed on data of day 2/3 transfers but was successfully validated on treatments with transfers performed on various days – from day 2 to day 6. This means that the day of embryo transfer does not affect the chance of live birth if all other important factors are known.',
  aboutH2_5: 'Stimulation protocol',
  aboutP5_1: 'We developed our model on stimulations carried out with the long GnRHa protocol and with the GnRH antagonist protocol. The type of protocol used did not affect the final results and was not important for calculating the chance of live birth after fresh and cryopreserved transfer(s).',
  aboutH2_6: 'What is a top-quality embryo?',
  aboutP6_1: 'To put it simply, a top-quality embryo is one that has the best quality and the highest chance to implant into the uterus! Embryo quality is based upon its morphology (the way it looks under the microscope) and not upon its genetic composition. At present, genetic diagnosis of an embryo is time-consuming, expensive and not 100% accurate, which is why most embryologists rely on morphological grading of their embryos.',
  aboutP6_2: 'We use the following top-embryo classifications:',
  aboutP6_3: 'For embryos on day 2 and 3, a top-quality embryo had even-sized blastomeres (cells), one nucleus per cell, <20% fragmentations and 4-5 cells (day 2) or >7 cells (day 3). This is based on van Royen’s classification (Van Royen E, Mangelschots K, De Neubourg D, Valkenburg M, Van de Meerssche M, Ryckaert G, Eestermans W, Gerris J. Characterization of a top-quality embryo, a step towards single-embryo transfer. Hum Reprod 1999; 14: 2345-2349).',
  aboutP6_4: 'For blastocysts, we use Gardner’s classifications (Gardner, D., Lane, M., Stevens, J., Schlenker, T., Schoolcraft, W.B., 2000. Blastocyst score affects implantation and pregnancy outcome: towards a single blastocyst transfer. Fertil. Steril. 73, 1155–1158).',
  aboutH2_7: 'Info',
  code: 'Code:',
  aboutP7_1: 'This site was created as a collaborative project between the University of Helsinki and Metropolia University of Applied Sciences. Here are the people that are directly responsible for the site:',
  val_age_1: 'Age has to be a number.',
  val_age_2: 'Minimum age should be at least 18 years.',
  val_age_3: 'Maximum age should be under 48 years.',
  val_dose_1: 'Dose has to be a number.',
  val_dose_2: 'Dose is required.',
  val_ooc_1: 'Value is required.',
  val_ooc_2: 'Value has to be a number.',
  val_ooc_3: 'The number of oocytes cannot be less than the number of cleaving embryos.',
  val_ooc_4: 'The number of oocytes cannot be less than the number of top-quality embroys.',
  val_clv_1: 'Value is required.',
  val_clv_2: 'Value has to be a number.',
  val_clv_3: 'The number of cleaved embryos cannot be higher than the number of oocytes.',
  val_top_1: 'Value is required.',
  val_top_2: 'Value has to be a number.',
  val_top_3: 'The number of top-quality embryos cannot be higher than the number of cleaved embryos.',
  val_top_4: 'The number of top-quality embryos cannot be higher than the number of oocytes.',
  val_diag_1: 'Diagnosis is required.',
  val_age_4: 'Age cannot decrease between stimulations.',
  val_age_5: 'Age is required.',
  fb_1: 'Click here to leave feedback',
  fb_2: 'Hide feedback form',
  fb_3: 'Your feedback (max 1000 chars.):',
  fb_4: 'Submit',
  fb_5: 'Your feedback has been sent.',
  username: 'Username',
  password: 'Password',
  set_ad_1: 'Add new user',
  pass_again: 'Re-type password',
  set_ad_2: 'Admin privilege: ',
  set_ad_3: 'Save user',
  new_pass: 'New password',
  set_ad_4: 'Update password',
  set_ad_5: 'Update',
  set_ad_6: 'Feedback:',
  set_u_title: '1-15 chars, no spaces',
  set_pw_title: '4-10 chars, no spaces',
  set_rm: 'delete',
  set_ad_7: 'List of current users:',
  set_added: 'added.',
  set_failed_1: 'Action failed.',
  set_failed_2: 'Password has to be between 4-10 characters long.',
  set_failed_3: 'Username length at most 15 characters.',
  set_failed_4: 'No spaces.',
  set_remove_1: 'Do you wish to remove',
  set_remove_2: 'from having database access?',
  set_passupdate: 'Password updated',
  loginSign: 'Sign in',
  loginFail: 'Login failed.',
  printAdditional: 'Additional information',
  printNotChosen: 'Not chosen',
  hy: 'University of Helsinki',
  metropol: 'Metropolia UAS',
  students: 'Students of Metropolia:',
  version: 'Version: '
};
