export const fi = {
  code: 'Koodi:',
  naviHello: 'Hei,',
  naviHome: 'Etusivu',
  naviLogin: 'Kirjaudu',
  naviSettings: 'Asetukset',
  naviData: 'Data',
  naviAbout: 'Lisätietoja',
  naviLogout: 'Kirjaudu ulos',
  labelAge: 'Ikä',
  labelDose: 'Gonadotropiinin kokonaisanno, IU',
  labelOocytes: 'Kerättyjen munasolujen määrä',
  labelCleaving: 'Jakautuvien alkioiden määrä päivänä 2/3',
  labelTop: 'Top-alkioiden määrä päivänä 2/3',
  stimulation: 'Hoitokerta',
  labelDiagnosis: 'Diagnoosi',
  labelStatus: 'Asema',
  labelDoctor: 'Lääkäri',
  labelPatient: 'Potilas',
  btnSubmit: 'Lähetä',
  addStimulation: 'Lisää hoitokerta',
  rmvStimulation: 'Poista hoitokerta',
  selectChoose: 'Valitse',
  selectUnexplained: 'Selittämätön',
  selectEndo: 'Endometrioosi',
  selectAno: 'Ovulaatiohäiriö',
  selectMalef: 'Miehestä johtuva',
  selectTubal: 'Munajohdinvika',
  mainTitle: 'Elävän lapsen syntymän todennäköisyys IVF/ICSI-hoidon jälkeen',
  mainContent1: 'Tämä sivu laskee synnytyksen todennäköisyyden, kun on tehty yksi tai useampi IVF/ICSI–hoito käyttäen pariskunnan omia sukusoluja (munasoluja ja siittiöitä). Hoitokertojen arviointi sisältää myös kaikki pakastettujen alkioiden siirrot. Mahdollisimman tarkkojen ennusteiden saavuttamiseksi laskurilla käytämme mm. stimulaatiohoitokerran (ns. tuoresyklin) kliinisiä ja laborariotuloksia. Lisätietoja laskumenetelmistä löytyy',
  mainAbout: 'Lisätietoja',
  mainContent2: '-osasta.',
  infoTitle: 'Lisätietoa',
  infoAgeTitle: 'Ikä:',
  infoAge: 'naisen ikä vuosina munasolujen keräyspäivänä.',
  infoGonaTitle: 'Gonadotropiinin kokonaisannos, IU:',
  infoGona: 'stimulaation käytetty rekombinantti-FSH tai puhdistettu ihmisen menopausaalinen gonadotropiini, annos kansainvälisissä yksiköissä ilmaistuna.',
  infoOocTitle: 'Kerättyjen munasolujen määrä:',
  infoOoc: 'kerättyjen munasolujen määrä sisältäen kypsät ja epäkypsät munasolut.',
  infoCleavTitle: 'Jakautuvien alkioiden määrä, päivä 2/3:',
  infoCleav: 'jos siirto tehdään päivänä 2, kirjoita jakautuvien alkioiden määrä päivänä 2. Kaikissa muissa tapauksissa kirjoita jakautuvien alkioiden määrä päivänä 3.',
  infoTopTitle: 'Top-alkioiden määrä päivänä 2/3:',
  infoTop1: 'jos siirto tehdään päivänä 2, kirjoita top-alkioiden määrä päivänä 2. Kaikissa muissa tapauksissa kirjoita top-alkioiden määrä päivänä 3. Alkioluokituskriteerit löytyy',
  infoTopAbout: 'Lisätietoja',
  infoTop2: '-osasta',
  infoDiagnosisTitle: 'Diagnoosi:',
  infoDiagnosis: 'valitse yksi lapsettomuuden päädiagnoosi.',
  addUser: 'Lisää käyttäjä',
  username: 'Käyttäjänimi',
  password: 'Salasana',
  old_password: 'Vanha salasana',
  new_password: 'Uusi salasana',
  admin_country: 'Maa',
  admin_status: 'Asema',
  admin_diagnosis: 'Diagnoosi',
  admin_age: 'Ikä',
  admin_dose: 'Annos',
  admin_oocytes: 'Munasolut',
  admin_cleaving: 'Jakautuvat',
  admin_top: 'Top',
  admin_stimulation: 'Stimulaatio',
  admin_cumulative_probability: 'Kumulatiivinen todennäköisyys',
  admin_probability: 'Todennäköisyys',
  admin_date: 'Päivämäärä',
  admin_start_date: 'Alku päivä',
  admin_end_date: 'Loppu päivä',
  admin_filter: 'Suodata',
  admin_export: 'Vie Exceliin',
  chart_cumulative_probability: 'Kumulatiivinen ennuste jo tehdyistä stimulaatiohoidoista',
  chart_max_cumulative: 'Maksimi kumulatiivinen ennuste',
  chart_min_cumulative: 'Minimi kumulatiivinen ennuste',
  chart_x_axis_label: 'Hoitokerta',
  chart_y_axis_label: 'Synnytysennuste hoidon jälkeen',
  aboutH1: 'Lisätietoja',
  aboutH2_1: 'Miten ennusteet lasketaan?',
  aboutP1_1: 'Tämän laskurin tilastolliset perusteet ovat suomalaisesta retrospektiivisesta tutkimuksesta, jossa analysoitiin 13,000 munasarjastimulaatiokiertoa IVF/ICSI-hoitoa varten, sekä näitä seuranneet 10,000 pakastetun alkion siirtoa (PAS). Tutkimuksessa käytettiin tietoja Helsingin, Oulun ja Tampereen yliopistollisten sairaaloiden lapsettomuusyksiköissä sekä Väestöliiton Helsingin ja Oulun lapsettomuusklinikoissa tehdyistä hoidoista. (Development and external validation of prediction model for cumulative live birth after IVF/ICSI using ovarian response and embryo cohort quality data of 11,461 Finnish women, kirjoittajat Zdravka Veleva, Henna Oksanen, Anna But, Sirpa Mäkinen, Helena Tinkanen, Christel Hydén-Granskog, Niklas Simberg, Hannu Martikainen, Aila Tiitinen, ja  Juha S. Tapanainen).',
  aboutP1_2: 'Täytä hoitokertasi tiedot laskeaksesi hoitotuloksen ennusteen. Laskuri antaa ennusteen tuorealkionsiirron ja kaikista saman stimulaatiokerran pakastettujen alkioiden siirtojen lopputuloksesta.',
  aboutP1_3: 'Voit myös laskea synnytysennusteen käyttämällä useamman kuin yhden hoitokerran tietoja. Laskuri näyttää kumulatiivisen todennäköisyyden synnytyksen onnistumiselle viidenteen stimulaatiosykliin asti.',
  aboutP1_4: 'Synnytyksen ennusteet hoidoista, joita ei vielä toteutettu: olemassa olevien tietojen perusteella laskuri antaa optimistisen ja pessimistisen ennusteen. Ennusteet perustuvat parhaiten ja huonoiten onnistuneen hoitokertasi tietoihin. Jos sinulle on tehty vain yksi stimulaatiohoito, laskuri tekee ennusteet pelkästään tämän syklin tietojen pohjalta.',
  aboutP1_5: 'Laskurin ennusteet eivät riipu tuoresiirron alkioiden määrästä, siirron ajankohdasta (jos siirto on tehty päivien 2 – 6 aikana), tai munasarjastimulaation tyypistä. Syynä tähän on se, että laskuri käyttää tehokkaampia ennustetekijöitä, kuin siirrettyjen alkioiden määrä, siirron päivämäärä tai stimulaаtion tyyppi.',
  aboutH2_2: 'Kuinka tarkkoja ennusteet ovat?',
  aboutP2_1: 'Tämä laskuri antaa tällä hetkellä tarkimman ennusteen IVF/ICSI ja PAS-hoitojen jälkeisen synnytyksen onnistumiselle. Ennusteisiin kuitenkin liittyy tietty määrä epävarmuutta, koska joitakin ominaisuuksia ei pystytä täysin arvioimaan, etenkin alkioiden geneettiseen koostumukseen ja pakastettujen alkioiden siirtoihin liittyvät tekijät. ',
  aboutP2_2: 'Meidän isossa suomalaisessa tutkimuksessa ennustemallin tehoa arvioitiin usealla eri tavalla. Malli pystyy erottamaan ne potilaat ja hoidot, joilla on korkea synnytyksen onnistumistodennäköisyys, niistä, joilla onnistumistodennäköisyys on matala, faktorilla 0.72. Vertailuna, 0.50 on satunnaisen arvauksen teho ja 1.00 on täydellinen yhtäläisyys kliiniseen tulokseen. Mallin ennustamat ja todelliset todennäköisyydet olivat kuitenkin hyvin lähellä toisiaan ja P-arvo oli 0.99 (P=1.0 on täydellinen yhtäläisyys).',
  aboutP2_3: 'Tämän nettisivun tarkoitus on antaa neuvoja ja havainnollistaa, miten erilaiset tausta- ja hoitotekijät yhdessä vaikuttavat onnistuneen synnytyksen todennäköisyyteen. Jos haluat tarkempia tietoja, kysythän lisää lääkäriltäsi!',
  aboutH2_3: 'Siirettyjen alkioiden määrä',
  aboutP3_1: 'Synnytyksen todennäköisyys on sama yhden ja kahden alkion siirron jälkeen, jos siirretään enintään yksi top-alkio. Yli yhden top-alkion siirtoa ei suositella kohonneen kaksosraskauden ja komplikaatioiden riskin vuoksi. Jos tuoresiirrossa siirretään vain yksi alkio, jää pariskunnalle enemmän alkioita, jotka voidaan pakastaa ja siirtää myöhemmin.',
  aboutH2_4: 'Alkionsiirtopäivä',
  aboutP4_1: 'Ennustemalli kehitettiin päivän 2/3 siirroista, mutta se validoitiin onnistuneesti päivien 2-6 siirtohoidoilla. Tämä tarkoittaa sitä, että alkion siirtopäivä ei vaikuta synnytyksen mahdollisuuteen, jos kaikki muut tärkeät tekijät pystytään ottamaan huomioon. ',
  aboutH2_5: 'Stimulaatioprotokolla',
  aboutP5_1: 'Ennustemalli kehitettiin stimulaatioilla, jotka tehtiin joko pitkällä GnRH-protokollalla tai GnRH-antagonistiprotokollalla. Protokollatyyppi ei vaikuttanut lopputuloksiin eikä ollut merkittävä tuore- ja pakastussiirtojen jälkeisen synnytyksen onnistumisennusteen kannalta.',
  aboutH2_6: 'Mikä on top-alkio?',
  aboutP6_1: 'Lyhyesti, top-alkio on sellainen alkio, jonka laatu on paras mahdollinen ja sillä on korkein todennäköisyys kiinnittyä kohtuun. Alkion laatu tässä työssä perustuu sen morfologiaan (eli miltä se näyttää mikroskoopin alla), eikä sen geneettiseen koostumukseen. Tällä hetkellä alkion geneettinen diagnoosi on aikaavievä, kallis ja epätarkka menetelmä, mistä syystä suurin osa embryologeista luottaa ainoastaan alkioiden morfologiseen luokitukseen.',
  aboutP6_2: 'Käytämme seuraavia top-alkioiden luokituksia:',
  aboutP6_3: 'Päivän 2 ja 3 top-alkioilla on samankokoiset blastomeerit (solut), yksi tuma per solu, <20% fragmentaatiota ja 4-5 solua (päivä 2) tai >7 solua (päivä 3). Tämä perustuu van Royenin luokitteluun (Van Royen E, Mangelschots K, De Neubourg D, Valkenburg M, Van de Meerssche M, Ryckaert G, Eestermans W, Gerris J. Characterization of a top-quality embryo, a step towards single-embryo transfer. Hum Reprod 1999; 14: 2345-2349).',
  aboutP6_4: 'Blastokystien arviointiin käytämme Gardnerin luokittelua (Gardner, D., Lane, M., Stevens, J., Schlenker, T., Schoolcraft, W.B., 2000. Blastocyst score affects implantation and pregnancy outcome: towards a single blastocyst transfer. Fertil. Steril. 73, 1155–1158).',
  aboutH2_7: 'Tietoja',
  aboutP7_1: 'Tämä sivu on Helsingin yliopiston ja Metropolian ammattikorkeakoulun yhteisprojekti. Projektissa työskentelivät:',
  val_age_1: 'Ikä pitää olla numero.',
  val_age_2: 'Ikä pitää olla vähintään 18.',
  val_age_3: 'Ikä saa olla korkeintaan 48.',
  val_dose_1: 'Lääkeaineen määrä pitää olla numero.',
  val_dose_2: 'Lääkeaineen määrä pitää olla määritetty.',
  val_ooc_1: 'Munasolujen määrä pitää olla määritetty.',
  val_ooc_2: 'Munasolujen määrä pitää olla numero.',
  val_ooc_3: 'Munasolujen määrä ei saa alittaa jakautuvien alkioiden määrän.',
  val_ooc_4: 'Munasolujen määrä ei saa alittaa top-alkioiden määrän.',
  val_clv_1: 'Jakautuvien alkioiden määrä pitää olla määritetty.',
  val_clv_2: 'Jakautuvien alkioiden määrä pitää olla numero.',
  val_clv_3: 'Jakautuvien alkoiden määrä ei saa ylittää munasolumäärän.',
  val_top_1: 'Top-alkioiden määrä pitää olla määritetty.',
  val_top_2: 'Top-alkioiden määrä pitää olla numero.',
  val_top_3: 'Top-alkioiden määrä ei saa ylittää jakautuvien alkioiden määrän.',
  val_top_4: 'Top-alkioiden määrä ei saa ylittää munasolujen määrän.',
  val_diag_1: 'Diagnoosi pitää olla valittu.',
  val_age_4: 'Ikä ei saa pienentyä stimulaatioiden välillä.',
  val_age_5: 'Ikä pitää olla määritetty.',
  fb_1: 'Klikkaa jättääksesi palautetta',
  fb_2: 'Piilota palauteikkuna',
  fb_3: 'Sinun palautteesi (max. 1000 kirjainta):',
  fb_4: 'Lähetä',
  fb_5: 'Palautteesi lähetettiin.',
  set_ad_1: 'Lisää uusi käyttäjä',
  pass_again: 'Toista salasana',
  set_ad_2: 'Admin-oikeudet: ',
  set_ad_3: 'Tallenna',
  new_pass: 'Uusi salasana',
  set_ad_4: 'Päivitä salasana',
  set_ad_5: 'Päivitä',
  set_ad_6: 'Palaute:',
  set_u_title: '1-15 merkkiä, ei välilyöntejä',
  set_pw_title: '4-10 merkkiä, ei välilyöntejä',
  set_rm: 'poista',
  set_ad_7: 'Lista käyttäjistä:',
  set_added: 'lisätty.',
  set_failed_1: 'Toiminto epäonnistui.',
  set_failed_2: 'Salasanan pitää olla 4-10 merkkiä pitkä.',
  set_failed_3: 'Käyttäjätunnus saa olla maksimissaan 15 merkkiä pitkä.',
  set_failed_4: 'Ei välilyöntejä.',
  set_remove_1: 'Haluatko poistaa käyttäjältä',
  set_remove_2: 'pääsyn tietokantaan?',
  set_passupdate: 'Salasana päivitetty',
  loginSign: 'Kirjaudu sisään',
  loginFail: 'Kirjautuminen epäonnistui.',
  printAdditional: 'Lisätiedot',
  printNotChosen: 'Ei valittu',
  hy: 'Helsingin yliopisto',
  metropol: 'Metropolia AMK',
  students: 'Metropolian opiskelijat:',
  version: 'Versio: '
};
